---
name: SkyGridGenerator
main: shoghicp\SkyGridGenerator\Plugin
version: 1.0.0
api: [3.0.0, 3.0.0-ALPHA10]
author: shoghicp
website: https://github.com/Blugin/SkyGridGenerator-PMMP
load: STARTUP
...